object_type: global_settings
overrides:
    "query.language.mdx.cellLimit.value": "300000000"
    "query.timeout": "120 minutes"
    "query.cache.eviction.entryAge": "90 minutes"
    "query.result.max_rows": "10000000"
    "query.language.dax.bypassIsBlank": "True"
    "query.factless.ignoreIncidentalFilter": "false"
    "query.includeComments.general.queryId": "true"
    "query.language.dax.blockDimModifiedMeasureFilters": "false"
    "query.drillthrough.max_rows": "3000000"
    "connection.pool.maxTimeout": "10 hours"
    "connection.pool.group.maxConnections": "200"
    "connection.pool.user.maxConnections": "50"
    "aggregate.incrementalUpdate.enabled": "true"
    "aggregate.speculative.allmember.enabled": "false"
    "aggregates.creation.timeout": "8 hours"
    "aggregates.systemGenerated.activeInstance.retentionLimit": "200"
    "aggregates.configuration.maximum_concurrent_materializations": "5"
    "xmla.auth.token.enabled": "true"
    "xmla.discover.properties.daxdialect": "superdaxmd"
    "dataSample.timeout": "120 minutes"
    "aggregates.create.allowExactDistinctCountMeasures.enabled": "true"
    "aggregates.prediction.checkForNonAdditiveMeasuresAndConstraints.enabled": "false"
    "bigquery.http.connectTimeout": "180 seconds"
    "bigquery.http.readTimeout": "180 seconds"
    "schema.userDefinedMember.defaultExcelPivotTableProperty": "true"
