object_type: global_settings
overrides:
    "xmla.auth.token.enabled": "true"
    "auth.xmla.kerberos.keytab": "/tmp/krb/atscale.keytab"
    "auth.xmla.kerberos.spn": "HTTP/bos-sust1-4.corp.atscale.com@SUPPT.ATSCALE.COM"
  
